Feature/aws boilerplate sync
apptension/django-restauth pull request #7
Opened 2020-06-05 07:36 UTC by szdrasiak

2020-06-05 07:45 UTC, aambrozkiewicz requested changes

2020-06-05 07:45 UTC, aambrozkiewicz commented on .env.example
> +DJANGO_SECRET_KEY=local
I would rather use randomly generated string for secrets

2020-06-05 07:45 UTC, aambrozkiewicz commented on .env.example
> +DB_CONNECTION={"dbname":"backend","username":"backend","password":"backend","host":"db","port":5432}
Variables here should use primitives, not json/dict structures

2020-06-05 07:45 UTC, aambrozkiewicz commented on .env.example
> +NGINX_SERVER_NAME=''
This file is for app related envs

2020-06-05 07:45 UTC, aambrozkiewicz commented on scripts/run.sh
> +sh /app/scripts/await_db.sh
Do we need this for production build?

2020-06-05 08:13 UTC, pziemkowski commented on .env.example
> +DB_CONNECTION={"dbname":"backend","username":"backend","password":"backend","host":"db","port":5432}
This is how AWS Database secret delivers DB_CONNECTION, so we need it in this format

2020-06-05 08:16 UTC, szdrasiak commented on scripts/run.sh
> +sh /app/scripts/await_db.sh
right I don't think we need this, @pziemkowski correct me if I'm wrong

2020-06-05 08:22 UTC, pziemkowski commented on scripts/run.sh
> +sh /app/scripts/await_db.sh
It's quite useful to check db connection and fail the container so early. I don't think django does that during startup, right? 
Could we rely on health checks now if we remove this await_db.sh? What do you think?

2020-06-05 08:24 UTC, pziemkowski commented on Dockerfile
> +  && apk add --virtual build-deps gcc python3-dev musl-dev \
Do we need all those libraries that weren't present in the image previously? 
Maybe we copied too much from a previous project.

2020-06-05 08:24 UTC, pziemkowski commented on docker-compose.yml
> +    external: true
newline

2020-06-05 09:13 UTC, szdrasiak commented on Dockerfile
> +  && apk add --virtual build-deps gcc python3-dev musl-dev \
I copied those from `aws-boilerplate`, do you need `bash git openssh wget` installed in backend image? I think `libev libev-dev` may be removed and I can add `apk del build-deps` so that will save ~48mb

2020-06-17 12:17 UTC, aambrozkiewicz requested changes

2020-06-17 12:17 UTC, aambrozkiewicz commented on docker-compose.yml
> +    command: ["./scripts/run_local.sh"]
To musi być jako array?

2020-06-17 12:17 UTC, aambrozkiewicz commented on restauth/settings.py
> +SECRET_KEY = env("DJANGO_SECRET_KEY", default="=+9on!eny7gevu*q9b#1e*0tsno4@s6d&i#tdueunh)wczt$$^")
Nie może istnieć nic takiego jak defaultowy klucz, którego unikalność wpływa na bezpieczeństwo. Powinien być dodatkowo wymagany

2020-06-17 12:17 UTC, aambrozkiewicz commented on restauth/settings.py
> +        "NAME": DB_CONNECTION.get("dbname"),
Lepiej użyć `[]` tak aby ich brak spowodował błąd

2020-06-17 12:17 UTC, aambrozkiewicz commented on scripts/run_local.sh
> +./scripts/wait-for-it.sh db:5432
Ten skrypt zrobi exit 0 po tym jak uzyska połączenie?

2020-06-17 12:25 UTC, szdrasiak commented on docker-compose.yml
> +    command: ["./scripts/run_local.sh"]
nie musi, ale z tego co sie orientuje, to dobra praktykjest wlasnie ta forma zapisu, bo wtedy inaczej `PID` jest ustawiany dzieki czemu nie ma problemow z przechwytywaniem sygnalow `SIGTERM` itd,

2020-06-17 12:38 UTC, szdrasiak commented on restauth/settings.py
> +        "NAME": DB_CONNECTION.get("dbname"),
wtedy bedzie sie wywalać podczas build w kroku `RUN python manage.py collectstatic --no-input`

2020-06-17 13:25 UTC, szdrasiak commented
> Dlaczego tutaj jest ten secret?

bo `collectstatic` wymaga zeby `SECRET_KEY` byl ustawiony inaczej wywala blad, dlatego przenioslem go do osobnego stage i w docelowym obrazie kopiuje tylko folder ze staticami, a dzieki temu zaden env nie jest ustawiony w docelowym obrazie

2020-06-17 13:29 UTC, aambrozkiewicz commented
> > Dlaczego tutaj jest ten secret?
> 
> bo `collectstatic` wymaga zeby `SECRET_KEY` byl ustawiony inaczej wywala blad, dlatego przenioslem go do osobnego stage i w docelowym obrazie kopiuje tylko folder ze staticami, a dzieki temu zaden env nie jest ustawiony w docelowym obrazie

Tylko ze `collectstatic` powinien być uruchamiany z pełni skonfigurowanej aplikacji, z tym samym secretem itd. W przyszłości jak bedziemy chcieli robic collectstatic np na bucketa S3 to pojawi się ten sam problem. 

Może istnieje możliwość wykonania collectstatic tak samo jak migracje? @pziemkowski Co myślisz?

2020-06-17 13:33 UTC, szdrasiak commented
> > > Dlaczego tutaj jest ten secret?
> > 
> > 
> > bo `collectstatic` wymaga zeby `SECRET_KEY` byl ustawiony inaczej wywala blad, dlatego przenioslem go do osobnego stage i w docelowym obrazie kopiuje tylko folder ze staticami, a dzieki temu zaden env nie jest ustawiony w docelowym obrazie
> 
> Tylko ze `collectstatic` powinien być uruchamiany z pełni skonfigurowanej aplikacji, z tym samym secretem itd. W przyszłości jak bedziemy chcieli robic collectstatic np na bucketa S3 to pojawi się ten sam problem.
> 
> Może istnieje możliwość wykonania collectstatic tak samo jak migracje? @pziemkowski Co myślisz?
a odpalanie `collectstatic` w `CMD` ? wtedy bedzie uzywac tych samych secretow co appka, tyle ze wtedy bedzie robione przy kazdym odpalniu

2020-06-17 15:04 UTC, pziemkowski commented
Jedyną opcją byłoby odpalanie collectstatic jako komendę w run.sh zanim uruchomimy sam backend. Inaczej podczas builda nie ma możliwości zrobić tego.

2020-06-18 09:32 UTC, aambrozkiewicz approved these changes

2020-06-18 10:59 UTC, merged